version: '3'

services:
   nginx:
      image: nginx:latest
      volumes:
         - ./nginx:/etc/nginx/conf.d
      ports:
         - "5001:80"

   back-end:
      build: ./
      expose:
         - "5000"